name: adventure
description: "Join other MNSTRs on an adventure!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.33.0
  grpc: ^5.0.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/environment/
    - assets/sounds/
  fonts:
    - family: Pixelify
      fonts:
        - asset: assets/fonts/PixelifySans-VariableFont_wght.ttf
